### ISSUE TITLE
Jekyll error: Could not locate the included file fragment-simpletable.html

### ISSUE THREAD

**Issue by iroCheese** [FHIR/sushi#1023]
Hi everyone!

I encountered a problem on my machine running Fedora 35 (Linux).
When running `./_genonce.sh` on an unmodified sushi project (directly after running `sushi --init`) it fails with the following error:

```## Memory (MB): Use = 303, Free = 748, Total = 1052, Max =8026
Run jekyll: jekyll build --destination "/home/samuel/naboto/APIs/sushi-test/ExampleIG/output" (in folder /home/samuel/naboto/APIs/sushi-test/ExampleIG/temp/pages) (00:16.0506)
Jekyll: Source: /home/samuel/naboto/APIs/sushi-test/ExampleIG/temp/pages         (00:16.0890)
Jekyll: Generating...                                                            (00:16.0891)
Jekyll has failed. Complete output from running Jekyll:   Liquid Exception: Could not locate the included file 'fragment-simpletable.html' in any of ["/home/myuser/sushi-test/ExampleIG/temp/pages/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point o (00:16.0931)
Note: Check that Jekyll is installed correctly                                   (00:16.0932)
Publishing Content Failed: Process exited with an error: 1 (Exit value: 1)       (00:16.0932)
                                                                                 (00:16.0932)
Use -? to get command line help                                                  (00:16.0932)
                                                                                 (00:16.0932)
Stack Dump (for debugging):                                                      (00:16.0932)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at org.hl7.fhir.igtools.publisher.Publisher.runJekyll(Publisher.java:6053)
	at org.hl7.fhir.igtools.publisher.Publisher.runTool(Publisher.java:5974)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:5335)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:960)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:798)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:9033)
```
Running `sushi .` on the same project does not show any errors or warnings.

I noticed that the _includes directory only contains a `fragment-simpleTable.html` (capital T), whereas the publisher seems to look for `fragment-simpletable.html`. I was able to reproduce this behavior on two other Fedora 35 and one Ubuntu Server 21 machines with **sushi v2.2.6**.

I first tried simply renaming the file but this doesn't work because the directory content is always deleted when trying to run `._genonce.sh`.
I tried multiple installing different jekyll versions (4.2.1 from fedora/ubuntu repos as well as 4.2.1 and 3.9.1 with gem).
I also tried manually copying older versions of publisher.jar into the input cache and skipping overriding the file when running `./_updatePublisher.sh`. All without success.

A possible reason might be that on Linux paths are case-sensitive. Thus running the same scripts might be fine on Windows. I'm not sure whether this is a sushi issue or one of the other components is responsible for this problem as I am not very familiar with the underlying architecture.

**Comment by cmoesel** [comment]
Hi @iroCheese! We don't maintain the `_genonce` and `_updatePublisher` scripts -- we get them from [here](https://github.com/HL7/ig-publisher-scripts).  We also don't maintain the part of the build system that manages templates or Jekyll.  SUSHI only builds the FHIR artifacts (like profiles) and helps w/ some config of the IG JSON file.

As it turns out, there is a discussion over on chat.fhir.org about the problem you're reporting here.  It appears to be a bug in the templates that was just introduced today.  They're working on a fix.  See the discussion here: https://chat.fhir.org/#narrow/stream/179252-IG-creation/topic/jekyll.2Ftemplate.20error

**Comment by iroCheese** [comment]
Thanks for the fast response!
I was able to resolve my issue by switching to the latest release.

For anyone who wants to do the same:
Change the line 
`template = fhir.base.template#current` in `ig.ini` to `template = fhir.base.template`. By leaving out the version the latest release is used. Releases from #current can be broken.

**Comment by cmoesel** [comment]
Thanks for the update and workaround!
