### ISSUE TITLE
SUSHI 3.0.0 does not work with npx

### ISSUE THREAD

**Issue by cmoesel** [FHIR/sushi#1288]
The following works fine:
```
fsh-sushi@2.10.2 -v
```

But this does not:
```
npx fsh-sushi@3.0.0 -v
```
It produces:
```
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module 'antlr4/error'
Require stack:
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/FSHErrorListener.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/FSHImporter.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/index.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/utils/MasterFisher.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/utils/index.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/fhirtypes/common.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/errors/InvalidTypeError.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/errors/index.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/fhirtypes/dataTypes.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/fhirtypes/index.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/export/StructureDefinitionExporter.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/export/index.js
- /Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/app.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._resolveFilename (/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/tsconfig-paths/lib/register.js:85:40)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/FSHErrorListener.js:5:17)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/FSHErrorListener.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/FSHImporter.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/import/index.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/utils/MasterFisher.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/utils/index.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/fhirtypes/common.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/errors/InvalidTypeError.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/errors/index.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/fhirtypes/dataTypes.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/fhirtypes/index.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/export/StructureDefinitionExporter.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/export/index.js',
    '/Users/cmoesel/.npm/_npx/57c2c3504e461a9d/node_modules/fsh-sushi/dist/app.js'
  ]
}
```

This also seems to prevent SUSHI from being successfully run from an npm script.

See: https://chat.fhir.org/#narrow/stream/215610-shorthand/topic/SUSHI.203.2E0.2E0.20-.20Error.3A.20Cannot.20find.20module.20'antlr4.2Ferror'/near/364383639

**Comment by nwhatt** [comment]
Anyone have any workarounds for this? 

Here's a repl with the issue reproduced: 
https://replit.com/@NickHatt/HotpinkDarkgreenFossil
