### ISSUE TITLE
macOS 10.15.3 | sushi 0.6.3 SyntaxError: Use of const in strict mode

### ISSUE THREAD

**Issue by ahenket** [FHIR/sushi#179]
Environment macOS 10.5.3 (latest beta version of macOS as of writing)

I did a fresh install of fsh-sushi 0.6.3 under nodejs 0.12.2. Install appears successful but running sushi just yields an error:

```
mbp:Nictiz ahenket$ sudo npm install -g fsh-sushi
Password:
npm WARN engine winston@3.2.1: wanted: {"node":">= 6.4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine temp@0.9.1: wanted: {"node":">=6.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine fs-extra@8.1.0: wanted: {"node":">=6 <7 || >=8"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine html-minifier@4.0.0: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine commander@4.1.0: wanted: {"node":">= 6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine request@2.88.0: wanted: {"node":">= 4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine tar@5.0.5: wanted: {"node":">= 8"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine fs-minipass@2.1.0: wanted: {"node":">= 8"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine minipass@3.1.1: wanted: {"node":">=8"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine minizlib@2.1.0: wanted: {"node":">= 8"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine har-validator@5.1.3: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine universalify@0.1.2: wanted: {"node":">= 4.0.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine clean-css@4.2.3: wanted: {"node":">= 4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine har-schema@2.0.0: wanted: {"node":">=4"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine winston-transport@4.3.0: wanted: {"node":">= 6.4.0"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine readable-stream@3.5.0: wanted: {"node":">= 6"} (current: {"node":"0.12.2","npm":"2.7.4"})
npm WARN engine punycode@2.1.1: wanted: {"node":">=6"} (current: {"node":"0.12.2","npm":"2.7.4"})
/usr/local/bin/sushi -> /usr/local/lib/node_modules/fsh-sushi/dist/app.js
fsh-sushi@0.6.3 /usr/local/lib/node_modules/fsh-sushi
├── ini@1.3.5
├── sax@1.2.4
├── commander@4.1.0
├── fs-extra@8.1.0 (universalify@0.1.2, jsonfile@4.0.0, graceful-fs@4.2.3)
├── antlr4@4.8.0
├── tar@5.0.5 (chownr@1.1.3, fs-minipass@2.1.0, yallist@4.0.0, minizlib@2.1.0, minipass@3.1.1, mkdirp@0.5.1)
├── temp@0.9.1 (rimraf@2.6.3)
├── request-promise-native@1.0.8 (stealthy-require@1.1.1, request-promise-core@1.1.3, tough-cookie@2.5.0)
├── @types/html-minifier@3.5.3 (@types/relateurl@0.2.28, @types/uglify-js@3.0.4, @types/clean-css@4.2.1)
├── winston@3.2.1 (is-stream@1.1.0, one-time@0.0.4, stack-trace@0.0.10, triple-beam@1.3.0, readable-stream@3.5.0, logform@2.1.2, winston-transport@4.3.0, diagnostics@1.1.1, async@2.6.3)
├── html-minifier@4.0.0 (commander@2.20.3, relateurl@0.2.7, he@1.2.0, param-case@2.1.1, camel-case@3.0.0, clean-css@4.2.3, uglify-js@3.7.6)
├── request@2.88.0 (is-typedarray@1.0.0, aws-sign2@0.7.0, oauth-sign@0.9.0, forever-agent@0.6.1, tunnel-agent@0.6.0, caseless@0.12.0, isstream@0.1.2, json-stringify-safe@5.0.1, safe-buffer@5.2.0, aws4@1.9.1, extend@3.0.2, performance-now@2.1.0, uuid@3.4.0, combined-stream@1.0.8, qs@6.5.2, form-data@2.3.3, mime-types@2.1.26, tough-cookie@2.4.3, http-signature@1.2.0, har-validator@5.1.3)
└── lodash@4.17.15
mbp:Nictiz ahenket$ sushi -v
/usr/local/lib/node_modules/fsh-sushi/dist/app.js:16
const path_1 = __importDefault(require("path"));
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
mbp:Nictiz ahenket$ sushi .
/usr/local/lib/node_modules/fsh-sushi/dist/app.js:16
const path_1 = __importDefault(require("path"));
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
mbp:Nictiz ahenket$ node -v
v0.12.2
```

**Comment by ahenket** [comment]
Apparently this error was due to an older version (0.12) of nodejs. https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode. 

Updating to the current version of nodejs fixed this.
