### ISSUE TITLE
Putting quotes around an Id causes SUSHI to crash

### ISSUE THREAD

**Issue by markkramerus** [FHIR/sushi#228]
I made the mistake of putting quotation marks around an Id in a Profile declaration, and got a crash. Here's the console window:
```
C:\Users\mkramer\Documents\GitHub\fsh-icare>sushi .
info: Checking local cache for hl7.fhir.r4.core#4.0.1...
info: Found hl7.fhir.r4.core#4.0.1 in local cache.
info: Importing FSH text...
error: mismatched input '"icare-care-plan-with-review"' expecting SEQUENCE
  File: C:\Users\mkramer\Documents\GitHub\fsh-icare\icare.fsh
  Line: 5
info: Preprocessed 1 documents with 1 aliases.
info: Loaded package hl7.fhir.r4.core#4.0.1
(node:20808) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getText' of null
    at FSHImporter.visitId (C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:375:30)
    at FSHImporter.visitSdMetadata (C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:328:57)
    at C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:160:66
    at Array.map (<anonymous>)
    at FSHImporter.parseProfileOrExtension (C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:160:14)
    at FSHImporter.visitProfile (C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:147:14)
    at FSHImporter.visitEntity (C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:128:18)
    at C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:123:18
    at Array.forEach (<anonymous>)
    at FSHImporter.visitDoc (C:\Users\mkramer\AppData\Roaming\npm\node_modules\fsh-sushi\dist\import\FSHImporter.js:122:22)
(node:20808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by markkramerus** [comment]
The consolation is that SUSHI did tell me where my error was, but the exit wasn't graceful.
