### ISSUE TITLE
Jekyll error during build

### ISSUE THREAD

**Issue by tanghaibao** [FHIR/sushi#840]
```
Jekyll: [33m    Liquid Warning: Liquid syntax error (line 21): [:open_square, "["] is not a valid expression in "{{[fmt]}}" in Practitioner-PractitionerExample01.{{[fmt]}}.html (00:23.0723)
Jekyll: [33m    Liquid Warning: Liquid syntax error (line 21): [:open_square, "["] is not a valid expression in "{{[fmt]}}" in Practitioner-PractitionerExample01.{{[fmt]}}.html (00:23.0723)
...
Note: Check that Jekyll is installed correctly                                   (00:23.0767)
Publishing Content Failed: Process exited with an error: 1 (Exit value: 1)       (00:23.0769)
                                                                                 (00:23.0770)
Use -? to get command line help                                                  (00:23.0770)
                                                                                 (00:23.0771)
Stack Dump (for debugging):                                                      (00:23.0772)
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:153)
	at org.hl7.fhir.igtools.publisher.Publisher.runJekyll(Publisher.java:5338)
	at org.hl7.fhir.igtools.publisher.Publisher.runTool(Publisher.java:5244)
	at org.hl7.fhir.igtools.publisher.Publisher.generate(Publisher.java:4711)
	at org.hl7.fhir.igtools.publisher.Publisher.createIg(Publisher.java:858)
	at org.hl7.fhir.igtools.publisher.Publisher.execute(Publisher.java:707)
	at org.hl7.fhir.igtools.publisher.Publisher.main(Publisher.java:7756)
```

I'm using sushi version v1.3.2.
Which jekyll version should I use? Thank you!

**Comment by markkramerus** [comment]
Can you update to the latest version of the IG Publisher? I have seen this problem before, and I think it is might be an IG Publisher problem rather than Jekyll.

**Comment by tanghaibao** [comment]
thanks. This is indeed the fix. 
The cause is that I had script `_updatePublisher.sh` from a previous repo built on `sushi 0.16.0`. This script had pointed to an outdated publisher JAR.
